language: elixir
elixir:
  - 1.3.4
  - 1.4.2
otp_release:
  - 19.3
  - 18.3
matrix:
  # newest/oldest pair
  exclude:
    - elixir: 1.4.2
      otp_release: 18.3
    - elixir: 1.3.4
      otp_release: 19.3
sudo: false
notifications:
  recipients:
    - milmazz@gmail.com
env:
  - MIX_ENV=test
script:
  - "mix do local.hex --force, deps.get, test"
cache:
  directories:
    - deps
