language: elixir
elixir: 1.6.1
otp_release: 20.3
sudo: false
notifications:
  recipients:
    - milmazz@gmail.com
env:
  - MIX_ENV=test
script:
  - mix format --check-formatted
  - mix test
cache:
  directories:
    - deps
