language: elixir
sudo: false
elixir:
  - 1.6
  - 1.8
otp_release:
  - 20.3
  - 21.1
notifications:
  recipients:
    - milmazz@gmail.com
env:
  - MIX_ENV=test
cache:
  directories:
    - deps
    - _build
    - ~/.mix
    - ~/.hex
jobs:
  include:
    - stage: format
      env:
        - MIX_ENV=dev
      script: mix format --check-formatted
      elixir: 1.6
    - stage: types
      env:
        - MIX_ENV=dev
      before_script: travis_wait 20 mix dialyzer --plt
      script: mix dialyzer --halt-exit-status
      elixir: 1.6
